import React from "react";
import "./style.css"
import Header from "../header"
import Footer from "../footer"
import ScrollTop from "../helper/scroolToTop";

function Privacypolicy() {
    return (
        <>
        <ScrollTop />
        <Header/>
            <div className="privacy-policy">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12">
                             <div className="content-wrps">
                                 <h3 className="privacyPolicy">Privacy policy</h3>
                                 <p>Effective date: 2022-01-01</p>
                                 <p>1. <b>Introduction</b></p>
                                 <p>Welcome to <b> Smart Finance</b>.</p>
                                 <p><b>Smart Finance</b> (“us”, “we”, or “our”) operates <b>www.smartfinancetoken.com</b> (hereinafter referred to as <b>“Service”</b>).</p>
                                 <p>Our Privacy Policy governs your visit to <b>www.smartfinancetoken.com</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
                                 <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
                                 <p>Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“agreement”</b>).</p>
                                 <p>2. <b>Definitions</b></p>
                                 <p><b>SERVICE</b> means the www.smartfinancetoken.com website operated by Smart Finance.</p>
                                 <p><b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                                 <p><b>COOKIES</b> are small files stored on your device (computer or mobile device).</p>
                                 <p><b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
                                 <p><b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p> <p><b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.</p>
                                 <p><b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                                 <p>3. <b>Information Collection and Use</b></p>
                                 <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                                 <p>4. <b>Types of Data Collected</b></p>

                                 <p><b>Usage Data</b></p>
                                 <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<b>“Usage Data”</b>).</p>
                                 <p>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                                 <p>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>

                                 <p><b>Tracking Cookies Data</b></p>
                                 <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                                 <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
                                 <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                                 <p>Examples of Cookies we use:</p>
                                 <p>0.1. <b>Session Cookies:</b> We use Session Cookies to operate our Service.</p>
                                 <p>0.2. <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.</p>
                                 <p>0.3. <b>Security Cookies:</b> We use Security Cookies for security purposes.</p>

                                 <p>5. <b>Use of Data</b></p>
                                 <p>Smart Finance uses the collected data for various purposes:</p>
                                 <p>0.1. to provide and maintain our Service;</p>
                                 <p>0.5. to gather analysis or valuable information so that we can improve our Service;</p>
                                 <p>0.6. to monitor the usage of our Service;</p>
                                 <p>0.7. to detect, prevent and address technical issues;</p>
                                 <p>6. <b>Retention of Data</b></p>
                                 <p>We will retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

                                 <p>9. <b>Security of Data</b></p>
                                 <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                                 <p>13. <b>Service Providers</b></p>
                                 <p>We may employ third party companies and individuals to facilitate our Service (<b>“Service Providers”</b>), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
                                 <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                                 <p>14. <b>Analytics</b></p>
                                 <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

                                 <p>17. <b>Links to Other Sites</b></p>
                                 <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                                 <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                                 <p>18. <b><b>Children’s Privacy</b></b></p>
                                 <p>Our Services are not intended for use by children under the age of 18 (<b>“Child”</b> or <b>“Children”</b>).</p>
                                 <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
                                 <p>19. <b>Changes to This Privacy Policy</b></p>
                                 <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                                 <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
                                 <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                                 <p>20. <b>Contact Us</b></p>
                                 <p>If you have any questions about this Privacy Policy, please contact us by email: <b>contact@smartfinancetoken.com</b>.</p>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        <Footer/>
        </>
    );
}

export default Privacypolicy;
